[pytest]
addopts =
    --cov=src
    --cov=services
    --cov-config=.coveragerc
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=80
    --ignore=tests/load
testpaths =
    tests
